### PR TITLE
[#2602] [JSDoc] Add missing documentation for botbuilder-dialogs-adaptive recognizers folder's root

### PR DESCRIPTION
**Pull request by denscollo**
Addresses #2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/tree/main/libraries/botbuilder-dialogs-adaptive) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes

- Ported documentation from botbuilder-dotnet
- Added documentation for the files inside `recognizers` folder's root.
- Added `@private` for private methods.
- Added `@protected` for protected methods.
- Added JSDoc comments in **6 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
image

### CODE REVIEW

**Comment by joshgummersall** [comment]
I'm basing this off `staging/docs` to get them merged and then we'll do a single CI pass and marge.

**Review by joshgummersall — APPROVED** [review]

**Comment by joshgummersall** [comment]
@denscollo can you resolve this merge conflict? Then we can land these all in a batch.

**Comment by denscollo** [comment]
@joshgummersall sure, we'll do it now! Thanks

**Comment by joshgummersall** [comment]
@denscollo I merged the `staging/docs` branch which, unfortunately, automatically closed this PR. Please reopen against `main` when the merge conflicts are resolved. Thanks!

**Pull request closed without merging**
