### PR TITLE
[PORT] Port enhancements to take/skip/resolve/compare functions

### PR DESCRIPTION
**Pull request by Danieladu**
# Description
Port some built-in function related updates into js SDK
## take/skip
Tolerate over-range operator in skip/take function
Original PR: https://github.com/microsoft/botbuilder-dotnet/pull/4879

## resolve
Add resolve function for resolving TimexProperty values to string values
Original PR: https://github.com/microsoft/botbuilder-dotnet/pull/4573

## greaterThan, greaterThanOrEqual, lessThan, lessThanOrEqual
List of affected functions：greaterThan, greaterThanOrEqual, lessThan, lessThanOrEqual
Add support of logical comparison in Adaptive-Expressions can compare Date object.
Original PR: https://github.com/microsoft/botbuilder-dotnet/pull/4788

# status
- [x] take/skip
- [x] resolve
- [x] greaterThan, greaterThanOrEqual, lessThan, lessThanOrEqual

### CODE REVIEW

**Comment by cosmicshuai** [comment]
Verified JSON error msg PR is no need to port. JSON.parse function will throw correct info about the position once an error encountered.

**Comment by boydc2014** [comment]
> Verified JSON error msg PR is no need to port. JSON.parse function will throw correct info about the position once an error encountered.

OK, cool, removing the json part now

**Review by boydc2014 — APPROVED** [review]

**Comment by boydc2014** [comment]
Hey, @joshgummersall, can you help check this one. This is a purely porting PR to align some functions behavior in expression behaviors with C#, with no changes in core logic. 

Since it touches the package.json (updating a dependency Recognizers-Text to 1.3.0), it will need your review and approval. And after this gets in, we will do a cherry pick this into R11. 

Sorry the late schedule, the reason for this is, we just know the previous auto-porting bot stop working, so we did a full check of R11 PRs to make sure we didn't miss any PR to port. And we found a few PRs listed above to be ported. Thanks.

**Review by joshgummersall — APPROVED** [review]
Looks good, I'll set up a cherrypick PR once the `main` build passes.

**Comment by joshgummersall** [comment]
@boydc2014 it looks like this package group is referenced in a few other places as well: https://github.com/microsoft/botbuilder-js/search?l=JSON&q=recognizers

Do we need to update these as well?

**Comment by ryub3n** [comment]
Hi, I am having issues with the typing indicator and it seems like the message sorting issue could be the culprit as mentioned by @stevkan.

**Pull request merged**
