### PR TITLE
Potential temporary patch for #420

### PR DESCRIPTION
**Pull request by benbrown**
This patch catches the invalid value from the number recognizer, which would clear our short term dependency on that library's fix being published

### CODE REVIEW

**Comment by iMicknl** [comment]
Isnt this fixed in the [release](https://github.com/Microsoft/Recognizers-Text/releases/tag/javascript-v1.1.0) of this morning? :-)

**Comment by benbrown** [comment]
Theoretically yes @iMicknl, but I'm having problems building against the 1.1.0 version of the number recognizer. It is throwing errors about bigNumber missing.

**Comment by johnataylor** [comment]
I just verified the fix in a stand alone Node project. Works great for '0' and 'zero'.

**I don't think we want this work around.**

**Comment by cleemullins** [comment]
@benbrown The build for this PR fails.

**Comment by benbrown** [comment]
@cleemullins yes, but it fails because of the issue in the sub-package that we're trying to fix :O

Sounds like we're going to fix the root issue, so I'm going to close this.

**Comment by benbrown** [comment]
This has been updated with a new test case to validate that we're getting 0s as expected.

**Pull request merged**
