### PR TITLE
fix: Updates fast-xml-parser to address "Prototype Pollution" vulnerability

### PR DESCRIPTION
**Pull request by giacomorebonato**
https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-3325616

#minor

## Specific Changes

  - 
  -
  -

### CODE REVIEW

**Review by ceciliaavila — CHANGES_REQUESTED** [review]
Hi @giacomorebonato, please check the unit tests, there's one failing in `expressionParser.test`. Also, you should include the updated yaml.lock file.

**Comment by giacomorebonato** [comment]
`j2xParser` was renamed in fast-xml-parser. I updated the code.

**Comment by giacomorebonato** [comment]
@microsoft-github-policy-service agree

**Review by ceciliaavila — APPROVED** [review]

**Comment by giacomorebonato** [comment]
Do you have any updates on this? Many thanks!

**Review by tracyboehrer — APPROVED** [review]

**Pull request merged**
