### PR TITLE
Fix for working with ServerlessFramework

### PR DESCRIPTION
**Pull request by wscholar**
Authorization was coming in empty because it was checking caps vs lowercase.

### CODE REVIEW

**Comment by cleemullins** [comment]
@benbrown Can you take a look? How are non-standard cased parameters normally handled in JS

**Comment by cleemullins** [comment]
@benbrown @Stevenic  The build is failing with this:

```
1) BotFrameworkAdapter
       should processActivity().:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/Microsoft/botbuilder-js/libraries/botbuilder/tests/botFrameworkAdapter.test.js)
  
  2) BotFrameworkAdapter
       should processActivity() sent as body.:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/Microsoft/botbuilder-js/libraries/botbuilder/tests/botFrameworkAdapter.test.js)
  
  3) BotFrameworkAdapter
       should return 500 error on bot logic exception during processActivity().:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/Microsoft/botbuilder-js/libraries/botbuilder/tests/botFrameworkAdapter.test.js)
  
  4) BotFrameworkAdapter
       should return bots 'invokeResponse'.:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/Microsoft/botbuilder-js/libraries/botbuilder/tests/botFrameworkAdapter.test.js)
  
  5) BotFrameworkAdapter
       should return 500 error if bot fails to return an 'invokeResponse'.:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/Microsoft/botbuilder-js/libraries/botbuilder/tests/botFrameworkAdapter.test.js)
  
```

**Comment by benbrown** [comment]
This is a reasonable approach to the problem, but I'm not sure why it broke the build. I'll check that out.

**Comment by wscholar** [comment]
Sounds good.  I will check as well in a few hours if it hasn't been resolved

**Comment by benbrown** [comment]
@wscholar - the tests are failing because, in the absence of either header, your code leaves the variable null, whereas the tests expect at least an empty string.

Can you change your implementation to:
`const authHeader: string = req.headers.authorization || req.headers.Authorization || '';`

This should have the same impact.

**Comment by benbrown** [comment]
Thanks for the contribution, @wscholar

**Pull request merged**
