### PR TITLE
Get rid of last axios dependency

### LINKED ISSUE #1301: [engineering] Use consistent http request library
**Is your feature request related to a problem? Please describe.**

We currently require several different http libraries across our js dependencies. This creates lots of extra stuff to download & install when we npm install.

These are the libraries I've found:

- node-fetch
- axios
- request
- request-promise

**Describe the solution you'd like**

We should standardize which library we use and remove other library usages. 

I'd recommend node-fetch as it is very lightweight and browser friendly if we ever need to have isomorphic js support from the SDK.

**Describe alternatives you've considered**

Alternatively, the Azure SDK team also recommends `axios`. It is less ideal for browser usage, imo, but browser isn't a critical scenario for us.

**Additional context**

[enhancement]

### PR DESCRIPTION
**Pull request by alopix**
Fixes #1301

## Description
There was only a single reference to axios left in the code. This should get rid of it and replace it with the library of your choice.

### CODE REVIEW

**Comment by cleemullins** [comment]
@stevengum This looks very interesting, but I don't think we can take it for R9. Does this look like an R10 candidate?

**Comment by stevengum** [comment]
We should definitely take it for R10; as @alopix indicated in the PR we have an issue that specifically mentions removing the last axios dependency.

**Comment by EricDahlvang** [comment]
imo, this PR should require a major version bump.  I would prefer an approach guaranteed to not break existing bots.  

Since the default is axios for 4.n, and axios settings can be altered external to the sdk (interceptors), it seems we should continue to use axios as the default and provide an easy way to override.

**Comment by stevengum** [comment]
As @EricDahlvang pointed out this PR is a breaking change, which we will have to weigh.

I'm also considering altering the way the SDKs conduct HTTP requests to allow for greater developer configurability and platform compatibility (i.e. Node.js vs Browser) which may change priorities and/or implementations.

**Comment by alopix** [comment]
As a workaround I actually changed the implementation "completely". So instead of using the dedicated `SkillHttpClient` (which is useless by now as the `forwardToSkill` method is not being used by the `SkillDialog` anymore, I created my own `abstract class SkillBotFrameworkClient implements BotFrameworkClient`:

`postActivity` is basically a copy if the `BotFrameworkHttpClient` except instead of calling `axios.post` it has an `abstract async forwardToSkill<T>(
    webResource: import('@azure/ms-rest-js').WebResource
  ): Promise<InvokeResponse<T>>;` which is being used to allow subclasses to actually perform the call to send data to the skill.
This makes it even more flexible in implementing anything to forward the HTTP request.

This allows using the original `AppCredential` signing process as in botbuilder around 4.5(?): `await appCredentials.signRequest(webResource)`.


Full example:
```
async postActivity<T>(
    fromBotId: string,
    toBotId: string,
    toUrl: string,
    serviceUrl: string,
    conversationId: string,
    activity: Activity
  ): Promise<InvokeResponse<T>> {
    const appCredentials = await this.getAppCredentials(fromBotId, toBotId);
    if (!appCredentials) {
      throw new Error(
        'SkillBotFrameworkClient.postActivity(): Unable to get appCredentials to connect to the skill'
      );
    }

    if (!activity) {
      throw new Error(
        'SkillBotFrameworkClient.postActivity(): missing activity'
      );
    }

    if (activity.conversation === undefined) {
      throw new Error(
        'SkillBotFrameworkClient.postActivity(): Activity must have a ConversationReference'
      );
    }

    // Get token for the skill call
    // TODO: could probably get rid of this, now that we use signRequest again
    const token = appCredentials.appId ? await appCredentials.getToken() : null;

    // Capture current activity settings before changing them.
    // TODO: DO we need to set the activity ID? (events that are created manually don't have it).
    const originalConversationId = activity.conversation.id;
    const originalServiceUrl = activity.serviceUrl;
    const originalRelatesTo = activity.relatesTo;
    const originalRecipient = activity.recipient;
    try {
      activity.relatesTo = {
        serviceUrl: activity.serviceUrl,
        activityId: activity.id,
        channelId: activity.channelId,
        conversation: {
          id: activity.conversation.id,
          name: activity.conversation.name,
          conversationType: activity.conversation.conversationType,
          aadObjectId: activity.conversation.aadObjectId,
          isGroup: activity.conversation.isGroup,
          properties: activity.conversation.properties,
          role: activity.conversation.role,
          tenantId: activity.conversation.tenantId
        },
        bot: null
      };
      activity.conversation.id = conversationId;
      activity.serviceUrl = serviceUrl;

      // Fixes: https://github.com/microsoft/botframework-sdk/issues/5785
      if (!activity.recipient) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        activity.recipient = {} as any;
      }

      const headers = {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        'User-Agent': USER_AGENT
      };

      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }

      const originalWebResource = new WebResource(
        toUrl,
        'POST',
        activity,
        undefined,
        headers
      );
      const webResource = appCredentials
        ? await appCredentials.signRequest(originalWebResource)
        : originalWebResource;

      const invokeResponse: InvokeResponse<T> = await this.forwardToSkill(
        webResource
      );
      return invokeResponse;
    } finally {
      // Restore activity properties.
      activity.conversation.id = originalConversationId;
      activity.serviceUrl = originalServiceUrl;
      activity.relatesTo = originalRelatesTo;
      activity.recipient = originalRecipient;
    }
  }
```

This way, there's no default dependency at all. It definitely is a breaking change, but so far, every release that had to do with the Skills SDK seems to have been a breaking change anyways.

**Comment by joshgummersall** [comment]
We will circle back on this issue after deciding on the backward-compatibility issues.

**Pull request closed without merging**
