### PR TITLE
rankerType got from options in QnA constructor

### LINKED ISSUE #1951: rankerType options left
## Versions
What package version of the SDK are you using. - JS botbuilder-ai 4.8.0
What nodejs version are you using - v10.16.3

## Describe the bug
Currently in QnAMaker class the constructor doesn't initialize the rankerType option.

https://github.com/microsoft/botbuilder-js/blob/9befacb893820b2b7863f03e72617cfb057e618c/libraries/botbuilder-ai/src/qnaMaker.ts#L84
```
 const {
            scoreThreshold = 0.3,
            top = 1,
            strictFilters = [] as QnAMakerMetadata[],
            metadataBoost = [] as QnAMakerMetadata[],
            timeout = 100000
        } = options;

        this._options = {
            scoreThreshold,
            top,
            strictFilters,
            metadataBoost,
            timeout
        } as QnAMakerOptions;
```
The only file this is referenced is in  qnamakerOptions.ts.
```
 /**
     * Id of the current question asked.
     */
    qnaId?: number;

    /**
     * A value indicating whether to call test or prod environment of knowledgebase. 
     */
    isTest?: boolean;

    /**
     * Ranker types.
     */
    rankerType?: string;
```

There is nothing else in the class that would assign rankerType tor QnAMaker options to actual values of argument of options were passed in.

## To Reproduce

Create instance of QnAMaker, passing in an option such as rankerType: "QuestionOnly".

We can use postman to see the spected behaviour: https://docs.microsoft.com/azure/cognitive-services/qnamaker/concepts/best-practices#choosing-ranker-type

## Expected behavior
QnAMaker class initializes values of options if passed in and only returns possible answers found only in questions.

### PR DESCRIPTION
**Pull request by deivkk**
Fixes #1951

## Description
rankerType option passed as option parameter in QnA constructor was ignored

## Specific Changes
- rankerType got from options parameters in QnA constructor
- unit test 'should call qnamaker with rankerType questionOnly' updated

## Testing
- no tests added, only above mentioned test has been updated

### CODE REVIEW

**Comment by deivkk** [comment]
Thanks @vipeketi for your comment.

Not sure if I understand you, do you refer to the unit test response json? If so, I have to accept that I couldn't test the real qna service after providing the rankerType option because I assume that the qna api keys are not published. So I opted to modify directly the mock.

If someone could provide the real answer from qna service for the updated unit test, I will adapt the mock.

**Comment by vipeketi** [comment]
It was not clear to me on why the test response was modified to empty list in test case, for this code change. It is clear to me now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by deivkk** [comment]
> This pull request can be automatically merged by project collaborators
Only those with write access to this repository can merge pull requests.

Who can do that?

**Comment by vipeketi** [comment]
Merged changes.

**Pull request merged**
