### PR TITLE
[#2602] [JSDoc] Add missing documentation for botbuilder-dialogs-adaptive converters/expressions/generators/luis/selectors folders

### PR DESCRIPTION
**Pull request by denscollo**
Addresses #2602

## Description
This PR adds all the missing JSDoc documentation for [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-dialogs-adaptive) based on the errors thrown. Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes

- Ported documentation from botbuilder-dotnet.
- Added documentation for the files inside `converters`, `expressions`, `generators`, `luis` and `selectors` folders.
- Added `@private` for private methods.
- Added JSDoc comments in **15 files**.

## Testing
In the following image there is a sneak peek about the ESLint Report with no JSDoc errors.
image

### CODE REVIEW

**Review by joshgummersall — APPROVED** [review]
👍

**Review by joshgummersall — CHANGES_REQUESTED** [review]
In an effort to improve generated docs, properly linking types with `[link text](xref:uid)` would be really helpful.

See more details [here](https://github.com/microsoft/botbuilder-js/pull/2838#discussion_r499724516) and [here](https://github.com/microsoft/botbuilder-js/pull/2838#discussion_r499748705).

**Review by joshgummersall — APPROVED** [review]

**Comment by joshgummersall** [comment]
Looks like a lint error?

**Comment by denscollo** [comment]
@joshgummersall Yes, we were fixing all conflicts on the rest of the PRs. We'll fix this issue now. Thanks!

**Comment by joshgummersall** [comment]
Thank you! Trying to get these all merged as soon as tests pass 👍

**Review by joshgummersall — APPROVED** [review]

**Pull request merged**
