### PR TITLE
Add LG samples 

### PR DESCRIPTION
**Pull request by ahmedlhanafy**
Samples included: 

1. 04.simple-prompt
2. 13.basic-bot
3. 53.book-table-bot

PS: This is a subsequent PR that should merged after this one https://github.com/Microsoft/botbuilder-js/pull/483

### CODE REVIEW

**Comment by cleemullins** [comment]
I'm not sure what to do with the. The PR is quite large, and covers several different areas. 

What would you suggest as the best way to review this? Perhaps as a group over a conf call?

**Comment by ahmedlhanafy** [comment]
This PR contains 2 things: 
1) Language generation code in `libraries/botbuilder-ai/tests/` and `libraries/botbuilder-ai/src/` which is already reviewed here https://github.com/Microsoft/botbuilder-js/pull/483 and should be merged before this PR
2) Language generation samples in `libraries/botbuilder-ai/samples`, which contains 3 samples: 
   - 04.simple-prompt: which is a direct port from https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/04.simple-prompt 
   - 13.basic-bot: also a direct port from https://github.com/ahmedlhanafy/botbuilder-js/tree/a-ahelh/lg_samples/libraries/botbuilder-ai/samples/13.basic-bot
   - 53.book-table-bot: this sample is new however it's adapted from the basic-bot sample

The changes in the samples are not significant, the notable changes are:
- `languageGenerationMiddleware.js`: which wraps around the language generation resolver and does the resolution
- `lgEntitiesState`: which stores the language generation entities which are then used in `languageGenerationMiddleware`
- `lgTemplateReferences.json`: which contains the language generation template references

**Comment by sgellock** [comment]
do not merge.  we no longer put samples into the language specific repos.  samples live in the appropriate branch of BotBuilder-sampels

**Comment by vishwacsena** [comment]
Had a chat with the team. We will move this to samples post 4.1. For now, its easier to keep the samples in the mslg branch since the packages will need to be built locally off of that branch so its easier to try samples from locally built packages.

**Pull request merged**
