### PR TITLE
Clean tslint errors and add to tslint test scripts

### PR DESCRIPTION
**Pull request by stevengum**
Files ignored:
- FileStorage, Table Storage
- Dialogs samples

### CODE REVIEW

**Comment by stevengum** [comment]
Build currently failing after #289 was merged

**Comment by stevengum** [comment]
I should note that while trying to build the botbuilder-prompts library the bug from #92 popped up again. I followed Steve's workaround and deleted `@types/react` from `node_modules/` which remedied the issue.

**Comment by cleemullins** [comment]
@stevengum Is it practical to get this in anytime soon?

**Comment by stevengum** [comment]
Closing due to major diffs in project and upcoming changes to the project's structure. Will either reopen or create new PR for tslint.

**Pull request closed without merging**
