### PR TITLE
Update Recognizers-Text to latest version

### PR DESCRIPTION
**Pull request by ceciliaavila**
## Description
This PR updates the version of the Recognizers-Text packages to the latest ([v.1.3.0](https://www.npmjs.com/package/@microsoft/recognizers-text/v/1.3.0))

## Specific Changes
Updated Recognizers-Text version in the following projects:
- adaptive-expressions
- botbuilder-ai
- botbuilder-dialogs
- testbot

## Testing
After updating the dependencies the tests ran successfully:

image

And the Testbot worked as expected:

image

### CODE REVIEW

**Comment by EricDahlvang** [comment]
It seems there are some regressions when comparing results to the previous version:



breaking changes:
```
month
was {"succeeded":true,"value":[{"timex":"2020-03","type":"daterange","start":"2020-03-01","end":"2020-04-01"}]}
now {"succeeded":false}
week
was {"succeeded":true,"value":[{"timex":"2020-W14","type":"daterange","start":"2020-03-30","end":"2020-04-06"}]}
now {"succeeded":false}
weekend
was {"succeeded":true,"value":[{"timex":"2020-W14-WE","type":"daterange","start":"2020-04-04","end":"2020-04-06"}]}
now {"succeeded":false}
year
was {"succeeded":true,"value":[{"timex":"2020","type":"daterange","start":"2020-01-01","end":"2021-01-01"}]}
now {"succeeded":false}
```

concerning:
```
till friday
was {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","end":"2020-03-27"},{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","end":"2020-04-03"}]}
now {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-03-27"},{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-04-03"}]}
untill friday
was {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","type":"date","value":"2020-03-27"},{"timex":"XXXX-WXX-5","type":"date","value":"2020-04-03"}]}
now {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-03-27"},{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-04-03"}]}

monday untill friday
was {"succeeded":true,"value":[{"timex":"XXXX-WXX-1","type":"date","value":"2020-03-30"},{"timex":"XXXX-WXX-1","type":"date","value":"2020-04-06"}]}
now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}
monday until friday
was {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-03-30","end":"2020-03-27"},{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-04-06","end":"2020-04-03"}]}
now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}
monday thru friday
was {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-03-30","end":"2020-03-27"},{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-04-06","end":"2020-04-03"}]}
now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}
monday to friday
was {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-03-30","end":"2020-03-27"},{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-04-06","end":"2020-04-03"}]}
now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}

from monday
was {"succeeded":true,"value":[{"timex":"XXXX-WXX-1","type":"date","value":"2020-03-30"},{"timex":"XXXX-WXX-1","type":"date","value":"2020-04-06"}]}
now {"succeeded":true,"value":[{"timex":"XXXX-WXX-1","Mod":"since","type":"daterange","sourceEntity":"datetimepoint","start":"2020-03-30"},{"timex":"XXXX-WXX-1","Mod":"since","type":"daterange","sourceEntity":"datetimepoint","start":"2020-04-06"}]}
```

less concerning, or derivatives of above:
```
light year
was {"succeeded":true,"value":[{"timex":"2020","type":"daterange","start":"2020-01-01","end":"2021-01-01"}]}
now {"succeeded":false}
maundy thursday
was {"succeeded":true,"value":[{"timex":"XXXX-WXX-4","type":"date","value":"2020-03-26"},{"timex":"XXXX-WXX-4","type":"date","value":"2020-04-02"}]}
now {"succeeded":false}
palm sunday
was {"succeeded":true,"value":[{"timex":"XXXX-WXX-7","type":"date","value":"2020-03-29"},{"timex":"XXXX-WXX-7","type":"date","value":"2020-04-05"}]}
now {"succeeded":false}
```

**Comment by ceciliaavila** [comment]
> It seems there are some regressions when comparing results to the previous version:
> 
> breaking changes:
> 
> ```
> month
> was {"succeeded":true,"value":[{"timex":"2020-03","type":"daterange","start":"2020-03-01","end":"2020-04-01"}]}
> now {"succeeded":false}
> week
> was {"succeeded":true,"value":[{"timex":"2020-W14","type":"daterange","start":"2020-03-30","end":"2020-04-06"}]}
> now {"succeeded":false}
> weekend
> was {"succeeded":true,"value":[{"timex":"2020-W14-WE","type":"daterange","start":"2020-04-04","end":"2020-04-06"}]}
> now {"succeeded":false}
> year
> was {"succeeded":true,"value":[{"timex":"2020","type":"daterange","start":"2020-01-01","end":"2021-01-01"}]}
> now {"succeeded":false}
> ```
> 
> concerning:
> 
> ```
> till friday
> was {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","end":"2020-03-27"},{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","end":"2020-04-03"}]}
> now {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-03-27"},{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-04-03"}]}
> untill friday
> was {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","type":"date","value":"2020-03-27"},{"timex":"XXXX-WXX-5","type":"date","value":"2020-04-03"}]}
> now {"succeeded":true,"value":[{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-03-27"},{"timex":"XXXX-WXX-5","Mod":"before","type":"daterange","sourceEntity":"datetimepoint","end":"2020-04-03"}]}
> 
> monday untill friday
> was {"succeeded":true,"value":[{"timex":"XXXX-WXX-1","type":"date","value":"2020-03-30"},{"timex":"XXXX-WXX-1","type":"date","value":"2020-04-06"}]}
> now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}
> monday until friday
> was {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-03-30","end":"2020-03-27"},{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-04-06","end":"2020-04-03"}]}
> now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}
> monday thru friday
> was {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-03-30","end":"2020-03-27"},{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-04-06","end":"2020-04-03"}]}
> now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}
> monday to friday
> was {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-03-30","end":"2020-03-27"},{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P3D)","type":"daterange","start":"2020-04-06","end":"2020-04-03"}]}
> now {"succeeded":true,"value":[{"timex":"(XXXX-WXX-1,XXXX-WXX-5,P4D)","type":"daterange","start":"2020-03-30","end":"2020-04-03"}]}
> 
> from monday
> was {"succeeded":true,"value":[{"timex":"XXXX-WXX-1","type":"date","value":"2020-03-30"},{"timex":"XXXX-WXX-1","type":"date","value":"2020-04-06"}]}
> now {"succeeded":true,"value":[{"timex":"XXXX-WXX-1","Mod":"since","type":"daterange","sourceEntity":"datetimepoint","start":"2020-03-30"},{"timex":"XXXX-WXX-1","Mod":"since","type":"daterange","sourceEntity":"datetimepoint","start":"2020-04-06"}]}
> ```
> 
> less concerning, or derivatives of above:
> 
> ```
> light year
> was {"succeeded":true,"value":[{"timex":"2020","type":"daterange","start":"2020-01-01","end":"2021-01-01"}]}
> now {"succeeded":false}
> maundy thursday
> was {"succeeded":true,"value":[{"timex":"XXXX-WXX-4","type":"date","value":"2020-03-26"},{"timex":"XXXX-WXX-4","type":"date","value":"2020-04-02"}]}
> now {"succeeded":false}
> palm sunday
> was {"succeeded":true,"value":[{"timex":"XXXX-WXX-7","type":"date","value":"2020-03-29"},{"timex":"XXXX-WXX-7","type":"date","value":"2020-04-05"}]}
> now {"succeeded":false}
> ```

Thanks @EricDahlvang , we'll check these issues.

**Comment by Stevenic** [comment]
Did the regressions ever get resolved?

**Comment by denscollo** [comment]
Hi @Stevenic 
We reviewed the regression tests and sent the conclussion to the team. We´re evaluating with them how to proceed with this.

**Comment by cleemullins** [comment]
@denscollo , @stevenic I'm hoping we can take this in R9. If not... R10.

**Comment by stevengum** [comment]
@ceciliaavila, @EricDahlvang, with issue #2124 it looks like this PR is missing [botbuilder-dialogs-adaptive](https://github.com/microsoft/botbuilder-js/blob/18cb9822fe4f1a745158ae532872c9db4f3f6e29/libraries/botbuilder-dialogs-adaptive/package.json#L23).

**Comment by joshgummersall** [comment]
This looks to have gone stale. Feel free to reopen if this gets updated.

**Pull request closed without merging**
