### PR TITLE
bugfix: fix inconsistent array initialization/concat in LuisRecognizerV2

### LINKED ISSUE #2521: Entity properties given inconsistent array nesting in LuisRecognizerOptionsV2
## Versions

botbuilder: 4.6.2",
botbuilder-ai: 4.6.2
nodejs: 10.16.3
OS: Windows

## Describe the bug
If a property that is an array is to be added via the LuisRecognierOptionsV2 addProperty method, the array is inconsistently destroyed or kept.  
They array holding the value is kept if the property is a new property.  If the key value of the property is not found on the object, the property will be added and the array holding the new value will be kept, resulting in a nested array at index 0.  (line 335 of LuisRecognizerOptionsV2).
The array is destroyed if the property key is already found to be present on the object.  Here, the concat method merges both arrays resulting in the loss of the array that held the value to be added.  (line 333 of LuisRecognizerOptionsV2)

The final result:  Property values that are held in arrays and added via this addProperty method will result in a nested array at index 0 and simple values being stored at all other indices.   The problem is shown in Screenshot 1.

## To Reproduce
1.  For this output data from our LUIS model:  {
  "query": "who is alexander van maren smith",
  "topScoringIntent": {
    "intent": "UserInfo",
    "score": 1.0
  },
  "intents": [
    {
      "intent": "UserInfo",
      "score": 1.0
    },
    {
      "intent": "None",
      "score": 2.42741339E-06
    },
    {
      "intent": "WhoOwnsWhat",
      "score": 6.58162833E-07
    }
  ],
  "entities": [
    {
      "entity": "alexander",
      "type": "PersonName",
      "startIndex": 7,
      "endIndex": 15,
      "score": 0.9996592,
      "role": "First"
    },
    {
      "entity": "van",
      "type": "PersonName",
      "startIndex": 17,
      "endIndex": 19,
      "score": 0.997405648,
      "role": "Last"
    },
    {
      "entity": "maren",
      "type": "PersonName",
      "startIndex": 21,
      "endIndex": 25,
      "score": 0.855693936,
      "role": "First"
    },
    {
      "entity": "smith",
      "type": "PersonName",
      "startIndex": 27,
      "endIndex": 31,
      "score": 0.9425993,
      "role": "Last"
    },
    {
      "entity": "alexander van maren smith",
      "type": "builtin.personName",
      "startIndex": 7,
      "endIndex": 31
    },
    {
      "entity": "alexander",
      "type": "PersonFName",
      "startIndex": 7,
      "endIndex": 15,
      "resolution": {
        "values": [
          "Alexander"
        ]
      }
    },
    {
      "entity": "van",
      "type": "PersonFName",
      "startIndex": 17,
      "endIndex": 19,
      "resolution": {
        "values": [
          "Van"
        ]
      }
    },
    {
      "entity": "alexander",
      "type": "PersonLastName",
      "startIndex": 7,
      "endIndex": 15,
      "resolution": {
        "values": [
          "Alexander"
        ]
      }
    },
    {
      "entity": "smith",
      "type": "PersonLastName",
      "startIndex": 27,
      "endIndex": 31,
      "resolution": {
        "values": [
          "Smith"
        ]
      }
    },
    {
      "entity": "who is",
      "type": "UserInfoIntentSynonyms",
      "startIndex": 0,
      "endIndex": 5,
      "resolution": {
        "values": [
          "UserInfo"
        ]
      }
    }
  ]
}

2. Use this LUIS response as and try to extract the PersonFName and PersonLastName entities from this after being processed by the LuisRecognizerV2.  

## Expected behavior
The nesting of arrays should be consistent, regardless of which index a value is being held at.  
Arrays to be added should either be consistently destroyed or kept, regardless if they are new property keys or not.
My proposed solution is shown in Screenshot2.
The other possible solution that would keep the array holding a property value, would need to avoid the use of the concat method.

## Screenshots
Screenshot1: 
Here is a screenshot of the inconsistent nesting of a property's values resulting from arrays being concatenated.  
image

Screenshot2:
Here is a screenshot for my suggested fix which will result in the array being consistently destroyed for a value stored at index 0.
image

Screenshot3:
Using the solution from Screenshot2, the object consistently concatenates the arrays resulting in a consistently nested object: 
image

## Additional context
We are currently blocked because of this, what is the proposed solution?  

[bug]

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #2521

### CODE REVIEW

**Comment by stevengum** [comment]
@munozemilio can you weigh in on this PR? There are some concerns that this might be a breaking change and/or not representative of the results from the LUIS APIs

**Comment by joshgummersall** [comment]
I verified that this produces results consistent with the LUIS API yesterday. The concern around breaking customer code is valid, though. I think it's worth discussing the implications.

**Comment by cleemullins** [comment]
Group consensus is that we leave this "as-is", as a change here is a breaking change.

**Comment by cleemullins** [comment]
Closed per @joshgummersall

**Pull request closed without merging**
