### PR TITLE
Upgrade Antlr

### LINKED ISSUE #3209: Upgrade antlr4ts library
## Description
adaptive-expressions and LG library depends on [antlr4ts](https://github.com/tunnelvisionlabs/antlr4ts) to parse expression and lg file.

Several days ago, `antlr4ts` release its new version contains such main updates:
- Upgrade typescript from 3.5.3 to 4.x
- Update antlr version from 4.7 to 4.9 directly.

## Expected behavior
Upgrade antlr version from [0.5.0-alpha.3](https://www.npmjs.com/package/antlr4ts/v/0.5.0-alpha.3) to [0.5.0-alpha.4](https://www.npmjs.com/package/antlr4ts/v/0.5.0-alpha.4) which would benefits from the more modern ECMAScript features in typescript 4.x

## References
Typescript upgrade issue: #1441
Typescript upgrade pr for other projects: #2990
[Release log](https://github.com/tunnelvisionlabs/antlr4ts/releases/tag/0.5.0-alpha.4)

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #3209

## Description
Upgrade antlr version and typescript version

### CODE REVIEW

**Comment by Danieladu** [comment]
@joshgummersall could you help to take a look at the failing tests in `consumer-test`. It seems Antlr breaks the typescript version which is < 3.6.

**Comment by joshgummersall** [comment]
It looks like `antlr4ts` introduced changes that are not compatible with Typescript<3.6. We aim to target, according to the consumer tests, Typescript >= 3.2.

There are two approaches here - the first is to introduce [`skipLibCheck`](https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck#56268670) for the adaptive expressions library (when used via Typescript < 3.6), which is not necessarily ideal but did fix the tests. The other is to try to introduce the use of `downlevel-dts` to the `antlr4ts` package to produce types that are valid for earlier Typescript versions.

**Comment by joshgummersall** [comment]
@Danieladu can you also mark the generated files (see https://github.com/microsoft/botbuilder-js/issues/3007 for more details).

**Comment by Danieladu** [comment]
@joshgummersall If we want to support TS (3.4, 3.5), maybe the first solution is not suitable.
I have filed an issue in antlr4ts repo to seek some advice. 
https://github.com/tunnelvisionlabs/antlr4ts/issues/499

No other opinions.
Close it temporarily, and would reopen this issue or PR if there exist some suitable solutions.

**Comment by joshgummersall** [comment]
@Danieladu I briefly started working on adding downlevel-dts support to the library. Maybe they will be receptive to a PR.

**Comment by Danieladu** [comment]
> @Danieladu I briefly started working on adding downlevel-dts support to the library. Maybe they will be receptive to a PR.

That is really great

**Pull request closed without merging**
