### PR TITLE
Revert "feat: immediate accept"

### PR DESCRIPTION
**Pull request by joshgummersall**
Reverts microsoft/botbuilder-js#2950

### CODE REVIEW

**Review by stevengum — COMMENTED** [review]
Why is this feature being reverted?

**Comment by joshgummersall** [comment]
@stevengum there was some impedance mismatch between what the Health Bot team wanted and what we delivered. Rather than leaving stale code in the SDK, it seems better to remove it.

Alternatively, if this still seems like something that other customers could make use of, we can just revert it from the `4.11` branch.

**Review by stevengum — APPROVED** [review]
@joshgummersall we should also revert it in `4.11` so that it isn’t accidentally shipped it in a patch release.

If we don’t want to lose the code, we could either put it on a branch and/or place it in a tracking issue; the benefit of the issue is that we’re less likely to lose track of it in future milestones...

Alternatively, there is the `BotBuilder-samples/experimental` route

**Comment by stevengum** [comment]
Since there is nothing pressing on this implementation being shipped, we’ll have more bake time for the requested feature.

**Pull request merged**
