### PR TITLE
Add functional tests package

### PR DESCRIPTION
**Pull request by ParadoxARG**
## Description
This pull request creates the `functional-tests` package for managing all the test that target services. We modified the NPM script that runs the functional tests, and modified the build pipeline with these changes.

## Specific Changes
- Move [botframework-connector/auth.test.js](https://github.com/southworkscom/botbuilder-js/blob/b61eb37a3a602b2e87bf57584670e124d73b7823/libraries/functional-tests/botframework-connector/auth.test.js) to [functional-test](https://github.com/southworkscom/botbuilder-js/tree/b61eb37a3a602b2e87bf57584670e124d73b7823/libraries/functional-tests) folder.
- Rename the `tests` folder inside `functional-tests` to `botframework`.
- Modify the [NPM script](https://github.com/southworkscom/botbuilder-js/blob/b61eb37a3a602b2e87bf57584670e124d73b7823/package.json#L8) that runs the functional tests.
- Remove hardcoded `appId` and `appPassword` from code and configure them as Azure Pipelines variables.

## Configuration
These changes require some small new configuration in the Azure Pipeline build.

Azure Pipelines uses the `build pipelines variables` as `environment variables` for the project if the name matches. This does not work with encrypted variables, so in order to use them encrypted we need to configure a `Powershell Task` to assign them.

The following guides show how to configure it using either the encrypted password or the decrypted one.

### With AppSecret encrypted
Add two variables called `authAppId` and `authAppPasswordEncripted`, and set their corresponding value.
image

Add a PowerShell script and configure it as follows:
image

### With AppSecret unencrypted
Add two variables named `authAppId` and `authAppPassword`, and assign their corresponding value.
image

## Testing
image
image

### CODE REVIEW

**Comment by ParadoxARG** [comment]
@cleemullins The changes were applied to the Pipelines configuration. This is ready to be merged.

**Comment by cleemullins** [comment]
@paradoxARG - Can you resolve the conflicts so we can take this?

**Comment by ParadoxARG** [comment]
Sure! We'll look into this.

**Comment by ParadoxARG** [comment]
@cleemullins Conflicts solved.

**Comment by cleemullins** [comment]
Closing out out of date due to current Functional Test Plan

**Pull request closed without merging**
